In [10]:
# https://my-json-server.typicode.com/st8324/repo/cafe
# 카페 매출 정보를 가져와서 DataFrame으로 변환하는 코드를 작성하세요
import requests
import pandas as pd
def cafe()->pd.DataFrame:
	url = 'https://my-json-server.typicode.com/st8324/repo/cafe'

	response = requests.get(url)

	try:
		response.raise_for_status()
		coffees = response.json()
		list = []
		labels = {
			'주문시간' : '주문시간',
			'메뉴' : '메뉴',
			'카테고리' : '카테고리',
			'수량' : '수량',
			'가격' : '가격',
			'결제수단' : '결제수단',
		}
		for coffee in coffees:
			dic = {}
			for column, label in labels.items():
				dic[column] = coffee[label]
			list.append(dic)
		return pd.DataFrame(list)
	except Exception as e:
		return pd.DataFrame()

In [13]:
# 카페 매출 정보를 가져오는 함수
cafe()

                주문시간     메뉴 카테고리  수량    가격   결제수단
0   2026-03-01 08:30  아메리카노   커피   1  4100     카드
1   2026-03-01 12:15   카페라떼   커피   2  4600     카드
2   2026-03-01 12:45  아메리카노   커피   1  4100     쿠폰
3   2026-03-02 09:10   카푸치노   커피   1  4800     카드
4   2026-03-02 13:20   카페라떼   커피   1  4600  카카오페이
5   2026-03-02 18:00  아메리카노   커피   3  4100     카드
6   2026-03-03 11:00  자몽에이드   음료   1  5500     카드
7   2026-03-03 15:30  아메리카노   커피   2  4100     현금
8   2026-03-04 08:00  아메리카노   커피   1  4100     카드
9   2026-03-04 12:00   카페라떼   커피   2  4600     카드
10  2026-03-04 13:00   카페라떼   커피   1  4600     카드
11  2026-03-05 14:00   샌드위치   푸드   1  6500  카카오페이

In [11]:
# 중복 및 결측치 처리하는 함수
def clean_cafe(df:pd.DataFrame)->pd.DataFrame:
	df = df.drop_duplicates()
	df = df.dropna()
	return df

In [12]:
# 확인
df = cafe()
clean_cafe(df)

                주문시간     메뉴 카테고리  수량    가격   결제수단
0   2026-03-01 08:30  아메리카노   커피   1  4100     카드
1   2026-03-01 12:15   카페라떼   커피   2  4600     카드
2   2026-03-01 12:45  아메리카노   커피   1  4100     쿠폰
3   2026-03-02 09:10   카푸치노   커피   1  4800     카드
4   2026-03-02 13:20   카페라떼   커피   1  4600  카카오페이
5   2026-03-02 18:00  아메리카노   커피   3  4100     카드
6   2026-03-03 11:00  자몽에이드   음료   1  5500     카드
7   2026-03-03 15:30  아메리카노   커피   2  4100     현금
8   2026-03-04 08:00  아메리카노   커피   1  4100     카드
9   2026-03-04 12:00   카페라떼   커피   2  4600     카드
10  2026-03-04 13:00   카페라떼   커피   1  4600     카드
11  2026-03-05 14:00   샌드위치   푸드   1  6500  카카오페이

In [ ]:
# 데이터를 활용한 예제