In [5]:
# https://my-json-server.typicode.com/st8324/repo/cafe
# 카페 매출 정보를 가져와서 DataFrame으로 변환하는 코드를 작성하세요
import requests
import pandas as pd
def cafe()->pd.DataFrame:
	url = 'https://my-json-server.typicode.com/st8324/repo/cafe'

	response = requests.get(url)

	try:
		response.raise_for_status()
		# coffees = response.json()
		# list = []
		# labels = {
		# 	'주문시간' : '주문시간',
		# 	'메뉴' : '메뉴',
		# 	'카테고리' : '카테고리',
		# 	'수량' : '수량',
		# 	'가격' : '가격',
		# 	'결제수단' : '결제수단',
		# }
		# for coffee in coffees:
		# 	dic = {}
		# 	for column, label in labels.items():
		# 		dic[column] = coffee[label]
		# 	list.append(dic)
		return pd.DataFrame(response.json())
	except Exception as e:
		return pd.DataFrame()

In [6]:
# 카페 매출 정보를 가져오는 함수
cafe()

                주문시간     메뉴 카테고리  수량    가격   결제수단
0   2026-03-01 08:30  아메리카노   커피   1  4100     카드
1   2026-03-01 12:15   카페라떼   커피   2  4600     카드
2   2026-03-01 12:45  아메리카노   커피   1  4100     쿠폰
3   2026-03-02 09:10   카푸치노   커피   1  4800     카드
4   2026-03-02 13:20   카페라떼   커피   1  4600  카카오페이
5   2026-03-02 18:00  아메리카노   커피   3  4100     카드
6   2026-03-03 11:00  자몽에이드   음료   1  5500     카드
7   2026-03-03 15:30  아메리카노   커피   2  4100     현금
8   2026-03-04 08:00  아메리카노   커피   1  4100     카드
9   2026-03-04 12:00   카페라떼   커피   2  4600     카드
10  2026-03-04 13:00   카페라떼   커피   1  4600     카드
11  2026-03-05 14:00   샌드위치   푸드   1  6500  카카오페이

In [7]:
# 중복 및 결측치 처리하는 함수
def clean_cafe(df:pd.DataFrame)->pd.DataFrame:
	df = df.drop_duplicates()
	df = df.dropna()
	return df

In [8]:
# 확인
df = cafe()
clean_cafe(df)

                주문시간     메뉴 카테고리  수량    가격   결제수단
0   2026-03-01 08:30  아메리카노   커피   1  4100     카드
1   2026-03-01 12:15   카페라떼   커피   2  4600     카드
2   2026-03-01 12:45  아메리카노   커피   1  4100     쿠폰
3   2026-03-02 09:10   카푸치노   커피   1  4800     카드
4   2026-03-02 13:20   카페라떼   커피   1  4600  카카오페이
5   2026-03-02 18:00  아메리카노   커피   3  4100     카드
6   2026-03-03 11:00  자몽에이드   음료   1  5500     카드
7   2026-03-03 15:30  아메리카노   커피   2  4100     현금
8   2026-03-04 08:00  아메리카노   커피   1  4100     카드
9   2026-03-04 12:00   카페라떼   커피   2  4600     카드
10  2026-03-04 13:00   카페라떼   커피   1  4600     카드
11  2026-03-05 14:00   샌드위치   푸드   1  6500  카카오페이

In [9]:
# 데이터를 활용한 예제
# 매출을 조회하기 위해 '결제액'을 추가
# 결제액은 가격 * 수량
df['결제액'] = df['가격']*df['수량']
print(df)

                주문시간     메뉴 카테고리  수량    가격   결제수단    결제액
0   2026-03-01 08:30  아메리카노   커피   1  4100     카드   4100
1   2026-03-01 12:15   카페라떼   커피   2  4600     카드   9200
2   2026-03-01 12:45  아메리카노   커피   1  4100     쿠폰   4100
3   2026-03-02 09:10   카푸치노   커피   1  4800     카드   4800
4   2026-03-02 13:20   카페라떼   커피   1  4600  카카오페이   4600
5   2026-03-02 18:00  아메리카노   커피   3  4100     카드  12300
6   2026-03-03 11:00  자몽에이드   음료   1  5500     카드   5500
7   2026-03-03 15:30  아메리카노   커피   2  4100     현금   8200
8   2026-03-04 08:00  아메리카노   커피   1  4100     카드   4100
9   2026-03-04 12:00   카페라떼   커피   2  4600     카드   9200
10  2026-03-04 13:00   카페라떼   커피   1  4600     카드   4600
11  2026-03-05 14:00   샌드위치   푸드   1  6500  카카오페이   6500

In [22]:
# 전체 매출액
revenue = df['결제액'].sum()
print(f'전체 매출액 : {revenue:,}원')

전체 매출액 : 77,200원

In [23]:
# 메뉴별 매출액을 조회(메뉴, 수량, 매출액)
# groupby
menu_df = df.groupby("메뉴")[['수량','결제액']].sum()
print(menu_df)

       수량    결제액
메뉴
샌드위치    1   6500
아메리카노   8  32800
자몽에이드   1   5500
카페라떼    6  27600
카푸치노    1   4800

In [45]:
# 카테고리별 수량과 결제액을 조회
# category_df = df.groupby('카테고리')[['수량','결제액']].sum()
# category_df = category_df.sort_values(by='결제액', ascending=False)
category_df = df.groupby('카테고리')[['수량','결제액']].sum().sort_values(by='결제액', ascending=False)

# 카테고리별 매출 비율을 추가
# 전체 매출액 : revenue
print(category_df)
category_df['매출비율'] = 100*category_df['결제액']/revenue
category_df['매출비율'] = category_df['매출비율'].round(1) # 소수점 두번째 자리에서 반올림
print(category_df)

# 매출이 가장 높은 카테고리를 조회
max_revenue = category_df['결제액'].max()
print(category_df.loc[category_df['결제액']==max_revenue])

print("--------")
max_revenue_idx = category_df['결제액'].idxmax() # 결재액 중 가장 큰 값을 가지는 위치
print(f'매출이 가장 많은 카테고리 : {max_revenue_idx}')
print("--------")
print(category_df.loc[max_revenue_idx])

      수량    결제액
카테고리
커피    15  65200
푸드     1   6500
음료     1   5500
      수량    결제액  매출비율
카테고리
커피    15  65200  84.5
푸드     1   6500   8.4
음료     1   5500   7.1
      수량    결제액  매출비율
카테고리
커피    15  65200  84.5
--------
매출이 가장 많은 카테고리 : 커피
--------
수량         15.0
결제액     65200.0
매출비율       84.5
Name: 커피, dtype: float64

In [49]:
# 시간대 별 주문 건수를 조회
# 시간대를 추가

df['주문시간'] = pd.to_datetime(df['주문시간'])
df['시간'] = df['주문시간'].dt.hour
print(df)

# 시간대 별 주몬 건수를 조회
hour_df = df['시간'].value_counts()

print(hour_df)

                  주문시간     메뉴 카테고리  수량    가격   결제수단    결제액  시간
0  2026-03-01 08:30:00  아메리카노   커피   1  4100     카드   4100   8
1  2026-03-01 12:15:00   카페라떼   커피   2  4600     카드   9200  12
2  2026-03-01 12:45:00  아메리카노   커피   1  4100     쿠폰   4100  12
3  2026-03-02 09:10:00   카푸치노   커피   1  4800     카드   4800   9
4  2026-03-02 13:20:00   카페라떼   커피   1  4600  카카오페이   4600  13
5  2026-03-02 18:00:00  아메리카노   커피   3  4100     카드  12300  18
6  2026-03-03 11:00:00  자몽에이드   음료   1  5500     카드   5500  11
7  2026-03-03 15:30:00  아메리카노   커피   2  4100     현금   8200  15
8  2026-03-04 08:00:00  아메리카노   커피   1  4100     카드   4100   8
9  2026-03-04 12:00:00   카페라떼   커피   2  4600     카드   9200  12
10 2026-03-04 13:00:00   카페라떼   커피   1  4600     카드   4600  13
11 2026-03-05 14:00:00   샌드위치   푸드   1  6500  카카오페이   6500  14
시간
12    3
8     2
13    2
9     1
18    1
11    1
15    1
14    1
Name: count, dtype: int64

In [54]:
# 시간대별로 매출액을 조회 : 오전(12시 이전), 오후(17시 이전), 저녁(17시 이후)
# 사간을 시간대로 변환하는 함수
def get_time_slot(hour):
	if hour < 12:
		return "오전"
	elif hour < 17:
		return "오후"
	else:
		return "저녁"

# 시간대를 출력
df['시간대'] = df['시간'].apply(get_time_slot)
print(df)

# 시간대 별 결제액을 조회
time_df=df.groupby('시간대')['결제액'].sum()
print(time_df)

                  주문시간     메뉴 카테고리  수량    가격   결제수단    결제액  시간 시간대
0  2026-03-01 08:30:00  아메리카노   커피   1  4100     카드   4100   8  오전
1  2026-03-01 12:15:00   카페라떼   커피   2  4600     카드   9200  12  오후
2  2026-03-01 12:45:00  아메리카노   커피   1  4100     쿠폰   4100  12  오후
3  2026-03-02 09:10:00   카푸치노   커피   1  4800     카드   4800   9  오전
4  2026-03-02 13:20:00   카페라떼   커피   1  4600  카카오페이   4600  13  오후
5  2026-03-02 18:00:00  아메리카노   커피   3  4100     카드  12300  18  저녁
6  2026-03-03 11:00:00  자몽에이드   음료   1  5500     카드   5500  11  오전
7  2026-03-03 15:30:00  아메리카노   커피   2  4100     현금   8200  15  오후
8  2026-03-04 08:00:00  아메리카노   커피   1  4100     카드   4100   8  오전
9  2026-03-04 12:00:00   카페라떼   커피   2  4600     카드   9200  12  오후
10 2026-03-04 13:00:00   카페라떼   커피   1  4600     카드   4600  13  오후
11 2026-03-05 14:00:00   샌드위치   푸드   1  6500  카카오페이   6500  14  오후
시간대
오전    18500
오후    46400
저녁    12300
Name: 결제액, dtype: int64

In [58]:
# 요일별 결제액 조회
df['요일'] = df['주문시간'].dt.dayofweek # dayofweek => 월 : 0, 화 : 1, .., 일 : 6
print(df)

                  주문시간     메뉴 카테고리  수량    가격   결제수단    결제액  시간 시간대  요일
0  2026-03-01 08:30:00  아메리카노   커피   1  4100     카드   4100   8  오전   6
1  2026-03-01 12:15:00   카페라떼   커피   2  4600     카드   9200  12  오후   6
2  2026-03-01 12:45:00  아메리카노   커피   1  4100     쿠폰   4100  12  오후   6
3  2026-03-02 09:10:00   카푸치노   커피   1  4800     카드   4800   9  오전   0
4  2026-03-02 13:20:00   카페라떼   커피   1  4600  카카오페이   4600  13  오후   0
5  2026-03-02 18:00:00  아메리카노   커피   3  4100     카드  12300  18  저녁   0
6  2026-03-03 11:00:00  자몽에이드   음료   1  5500     카드   5500  11  오전   1
7  2026-03-03 15:30:00  아메리카노   커피   2  4100     현금   8200  15  오후   1
8  2026-03-04 08:00:00  아메리카노   커피   1  4100     카드   4100   8  오전   2
9  2026-03-04 12:00:00   카페라떼   커피   2  4600     카드   9200  12  오후   2
10 2026-03-04 13:00:00   카페라떼   커피   1  4600     카드   4600  13  오후   2
11 2026-03-05 14:00:00   샌드위치   푸드   1  6500  카카오페이   6500  14  오후   3

In [64]:
df['주문시간'] = pd.to_datetime(df['주문시간'])
df['요일'] = df['주문시간'].dt.day_name()
dayweek_map = {
	'Monday' : '월요일',
	'Tuesday' : '화요일',
	'Wednesday' : '수요일',
	'Thursday' : '목요일',
	'Friday' : '금요일',
	'Satday' : '토요일',
	'Sunday' : '일요일',
}
df['요일'] = df['요일'].map(dayweek_map)
print(df)
# 카테고리 리스트
weekday_list = ['월요일','화요일','수요일','목요일','금요일','토요일','일요일']

# 요일을 카테고리 타입으로 변환
df['요일'] = pd.Categorical(df['요일'], categories=weekday_list, ordered=True)

# 요일별 결제액을 조회
weekday_df = df.groupby('요일')['결제액'].sum()

# 정렬
weekday_df = weekday_df.sort_index()

print(weekday_df)

                  주문시간     메뉴 카테고리  수량    가격   결제수단    결제액  시간 시간대   요일
0  2026-03-01 08:30:00  아메리카노   커피   1  4100     카드   4100   8  오전  일요일
1  2026-03-01 12:15:00   카페라떼   커피   2  4600     카드   9200  12  오후  일요일
2  2026-03-01 12:45:00  아메리카노   커피   1  4100     쿠폰   4100  12  오후  일요일
3  2026-03-02 09:10:00   카푸치노   커피   1  4800     카드   4800   9  오전  월요일
4  2026-03-02 13:20:00   카페라떼   커피   1  4600  카카오페이   4600  13  오후  월요일
5  2026-03-02 18:00:00  아메리카노   커피   3  4100     카드  12300  18  저녁  월요일
6  2026-03-03 11:00:00  자몽에이드   음료   1  5500     카드   5500  11  오전  화요일
7  2026-03-03 15:30:00  아메리카노   커피   2  4100     현금   8200  15  오후  화요일
8  2026-03-04 08:00:00  아메리카노   커피   1  4100     카드   4100   8  오전  수요일
9  2026-03-04 12:00:00   카페라떼   커피   2  4600     카드   9200  12  오후  수요일
10 2026-03-04 13:00:00   카페라떼   커피   1  4600     카드   4600  13  오후  수요일
11 2026-03-05 14:00:00   샌드위치   푸드   1  6500  카카오페이   6500  14  오후  목요일
요일
월요일    21700
화요일    13700
수요일    17900
목요일     6500
금요일        0
토요일        0
일요일    17400
Name: 결제액, dtype: int64

C:\Users\C603\AppData\Local\Temp\ipykernel_16768\866490517.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weekday_df = df.groupby('요일')['결제액'].sum()

In [ ]:
# 전체를 카페_매출.csv로 저장
df.to_csv('카페_매출.csv', index=False)

# 메뉴별 매출을 카페_메뉴_매출.csv로 저장
menu_df.to_csv('카페_메뉴_매출.csv')

# 카테고리별 매출을 카페_카테고리_매출.csv로 저장
category_df.to_csv('카페_카테고리_매출.csv')

# 시간대별 매출을 카페_시간_매출.csv로 저장
hour_df.to_csv('카페_시간_매출.csv')

# 요일별 매출을 카페_요일_매출.csv로 저장
weekday_df.to_csv('카페_요일_매출.csv')