In [10]:
import jpype
import os
# jvm 강제 종료
if jpype.isJVMStarted():
	jpype.shutdownJVM()

# 환경 변수에 JAVA_HOME이라는 변수를 등록
# 일반 문자열에서 \는 기능이 있음. \문자를 하려면 \\해야함
os.environ['JAVA_HOME'] = r'C:\Users\C603\Documents\AWS Class\ide\jdk\jdk-21'

In [11]:
# 데이터 생성
import pandas as pd
dataset = pd.read_csv('sample.csv')
# dataset.head(5)
# len(dataset)

In [21]:
# 전처리 결측치가 있으면 삭제
dataset=dataset.dropna()

In [22]:
# pip install konlpy

In [34]:
from konlpy.tag import Okt
# 형태소 분석. 명사, 동사, 형용사를 추출

# 데이터 프레임에 있는 sentence열을 가져와서 리스트로 변환
sentence = dataset['sentence'].tolist()

# sentences => cleaner_sentences로 변환
# 원본 문자열 => 필요한 형태소만 추출한 문자열 

okt = Okt()
cleaned_sentence = []
# 형태소 단위로 쪼갬
for text in sentence:
	# stem=True : 동사를 동사 원형으로 바꿈
	result = okt.pos(text, stem=True)
	# 반복문 결과를 리스트를 저장
	words = [word for word, pos in result if pos in ['Noun', 'Verb', 'Adjective']]
	# for word, pos in result:
	# 	# print(f'{word}({pos})')
		
	# 	# 단어의 품사가 명사, 동사, 형용사이면 추출하여 리스트에 추가
	# 	if pos in ['Noun', 'Verb', 'Adjective']:
	# 		words.append(word)
	# 리스트에 있는 단어들을 문자열로 변환 => 명사, 동사, 형용사만 있는 문자으로 변환
	new_text = " ".join(words)
	cleaned_sentence.append(new_text)
# 결과물 id, sentence, label, cleaned_sentence
dataset['cleaned_sentence'] = cleaned_sentence
dataset

    id                    sentence  label          cleaned_sentence
0    1     오늘 날씨가 정말 화창해서 기분이 최고예요      1       오늘 날씨 정말 화창하다 기분 최고
1    2         아침부터 일이 꼬여서 너무 짜증나요      0               아침 꼬이다 짜증나다
2    3      드디어 원하던 자격증 시험에 합격했습니다      1          원하다 자격증 시험 합격 하다
3    4     밤새 공부했는데 결과가 안 좋아서 우울해요      0     밤새 공부 하다 결과 안 좋다 우울하다
4    5    맛있는 음식을 먹으니 스트레스가 다 풀리네요      1        맛있다 음식 먹다 스트레스 풀리다
5    6      몸이 으슬으슬 떨리고 감기 기운이 있어요      0       몸 으슬으슬 떨리다 감기 기운 있다
6    7      친구들과 오랜만에 수다 떨어서 즐거웠어요      1            친구 만 수다 떨다 즐겁다
7    8     상사한테 혼나서 퇴사하고 싶은 마음뿐입니다      0       상사 혼나다 퇴사 싶다 마음 뿐이다
8    9      산책하며 좋아하는 노래를 들으니 행복해요      1     산책 하다 좋아하다 노래 들다 행복하다
9   10   길이 너무 막혀서 약속 시간에 늦을 것 같아요      0       길이 막히다 약속 시간 늦 것 같다
10  11         월급날이라 사고 싶었던 옷을 샀어요      1           월급 날 사고 싶다 옷 사다
11  12       지갑을 잃어버려서 하루 종일 막막합니다      0       지갑 잃어버리다 하루 종일 막막하다
12  13       부모님께 칭찬을 들어서 어깨가 으쓱해요      1      부모님 칭찬 들어서다 어깨 으쓱 하다
13  14  노트북이 갑자기 고장 나서 작업이 다 날아갔어요      0    노트북 갑자기 고장 나서다 작업 날아가다
14  15        주말에 푹 쉬었더니 에너지가 넘치네요      1           주말 푹 쉬다 에너지 넘치다
15  16       층간소음 때문에 잠을 한숨도 못 잤어요      0         층간소음 때문 잠 한숨 못 자다
16  17        여행 계획을 세우는 것만으로도 설레요      1           여행 계획 세우다 것 설레다
17  18        비가 계속 오니까 기분이 축 처지네요      0           비 계속 오 기분 축 처지다
18  19    오늘 점심 메뉴가 제가 제일 좋아하는 거예요      1      오늘 점심 메뉴 제 제일 좋아하다 거
19  20   프로젝트 마감이 내일인데 아직 갈 길이 멀어요      0       프로젝트 마감 내일 갈다 길이 멀다
20  21       새로 산 신발이 발에 딱 맞아서 기뻐요      1         새롭다 산 신발 발 맞다 기쁘다
21  22       믿었던 친구에게 실망해서 마음이 아파요      0         믿다 친구 실망하다 마음 아프다
22  23       창밖의 풍경이 너무 아름다워서 힐링돼요      1          창밖 풍경 아름답다 힐링 돼다
23  24   배달 음식이 한 시간 넘게 안 와서 화가 나요      0    배달 음식 하다 시간 넘다 안 오다 화가
24  25     좋아하는 연예인의 공연을 봐서 꿈만 같아요      1       좋아하다 연예인 공연 보다 꿈 같다
25  26     시험 범위가 너무 많아서 막막하고 답답해요      0        시험 범위 많다 막막하다 답답하다
26  27   오랜만에 가족들이 다 모여서 북적북적 즐겁네요      1          만 가족 모 북적 북적 즐겁다
27  28     운동하다가 발목을 삐어서 너무 고통스러워요      0          운동 하다 발목 삐 고통스럽다
28  29  직원들이 친절해서 쇼핑하는 내내 기분이 좋았어요      1    직원 친절하다 쇼핑 하다 내내 기분 좋다
29  30   컴퓨터 바이러스 때문에 중요한 문서가 깨졌어요      0   컴퓨터 바이러스 때문 중요하다 문서 깨지다
30  31       선물 받은 꽃다발 향기가 너무 향긋해요      1       선물 받다 꽃다발 향기 향 긋다 해
31  32      공들여 만든 요리를 태워버려서 속상합니다      0     공 만들다 요리 태우다 버리다 속상하다
32  33       아침 햇살을 받으며 일어나니 상쾌하네요      1        아침 햇살 받다 일어나다 상쾌하다
33  34        중요한 미팅인데 옷에 커피를 쏟았어요      0           중요하다 미팅 옷 커피 쏟다
34  35      보너스를 받아서 부모님 선물을 사드렸어요      1       보너스 받다 부모님 선물 사 드리다
35  36   사랑하는 사람과 헤어져서 눈물이 멈추지 않아요      0  사랑 하다 사람과 헤어지다 눈물 멈추다 않다

In [35]:
# 텍스트 전처리 함수
# 문장에서 명사, 동사, 형용사면 원형을 추출해서 문장을 만들어 반환
def text_preprocessing(text):
	# stem=True : 동사를 동사 원형으로 바꿈
	result = okt.pos(text, stem=True)
	# 반복문 결과를 리스트를 저장
	words = [word for word, pos in result if pos in ['Noun', 'Verb', 'Adjective']]
	return " ".join(words)

In [37]:
# text_preprocessing('오늘 날씨가 정말 화창해서 기분이 최고예요')
# '오늘 날씨 정말 화창하다 기분 최고'

dataset['cleaned_sentence2'] = dataset['sentence'].apply(text_preprocessing)
dataset[['cleaned_sentence','cleaned_sentence2']]

            cleaned_sentence         cleaned_sentence2
0        오늘 날씨 정말 화창하다 기분 최고       오늘 날씨 정말 화창하다 기분 최고
1                아침 꼬이다 짜증나다               아침 꼬이다 짜증나다
2           원하다 자격증 시험 합격 하다          원하다 자격증 시험 합격 하다
3      밤새 공부 하다 결과 안 좋다 우울하다     밤새 공부 하다 결과 안 좋다 우울하다
4         맛있다 음식 먹다 스트레스 풀리다        맛있다 음식 먹다 스트레스 풀리다
5        몸 으슬으슬 떨리다 감기 기운 있다       몸 으슬으슬 떨리다 감기 기운 있다
6             친구 만 수다 떨다 즐겁다            친구 만 수다 떨다 즐겁다
7        상사 혼나다 퇴사 싶다 마음 뿐이다       상사 혼나다 퇴사 싶다 마음 뿐이다
8      산책 하다 좋아하다 노래 들다 행복하다     산책 하다 좋아하다 노래 들다 행복하다
9        길이 막히다 약속 시간 늦 것 같다       길이 막히다 약속 시간 늦 것 같다
10           월급 날 사고 싶다 옷 사다           월급 날 사고 싶다 옷 사다
11       지갑 잃어버리다 하루 종일 막막하다       지갑 잃어버리다 하루 종일 막막하다
12      부모님 칭찬 들어서다 어깨 으쓱 하다      부모님 칭찬 들어서다 어깨 으쓱 하다
13    노트북 갑자기 고장 나서다 작업 날아가다    노트북 갑자기 고장 나서다 작업 날아가다
14           주말 푹 쉬다 에너지 넘치다           주말 푹 쉬다 에너지 넘치다
15         층간소음 때문 잠 한숨 못 자다         층간소음 때문 잠 한숨 못 자다
16           여행 계획 세우다 것 설레다           여행 계획 세우다 것 설레다
17           비 계속 오 기분 축 처지다           비 계속 오 기분 축 처지다
18      오늘 점심 메뉴 제 제일 좋아하다 거      오늘 점심 메뉴 제 제일 좋아하다 거
19       프로젝트 마감 내일 갈다 길이 멀다       프로젝트 마감 내일 갈다 길이 멀다
20         새롭다 산 신발 발 맞다 기쁘다         새롭다 산 신발 발 맞다 기쁘다
21         믿다 친구 실망하다 마음 아프다         믿다 친구 실망하다 마음 아프다
22          창밖 풍경 아름답다 힐링 돼다          창밖 풍경 아름답다 힐링 돼다
23    배달 음식 하다 시간 넘다 안 오다 화가    배달 음식 하다 시간 넘다 안 오다 화가
24       좋아하다 연예인 공연 보다 꿈 같다       좋아하다 연예인 공연 보다 꿈 같다
25        시험 범위 많다 막막하다 답답하다        시험 범위 많다 막막하다 답답하다
26          만 가족 모 북적 북적 즐겁다          만 가족 모 북적 북적 즐겁다
27          운동 하다 발목 삐 고통스럽다          운동 하다 발목 삐 고통스럽다
28    직원 친절하다 쇼핑 하다 내내 기분 좋다    직원 친절하다 쇼핑 하다 내내 기분 좋다
29   컴퓨터 바이러스 때문 중요하다 문서 깨지다   컴퓨터 바이러스 때문 중요하다 문서 깨지다
30       선물 받다 꽃다발 향기 향 긋다 해       선물 받다 꽃다발 향기 향 긋다 해
31     공 만들다 요리 태우다 버리다 속상하다     공 만들다 요리 태우다 버리다 속상하다
32        아침 햇살 받다 일어나다 상쾌하다        아침 햇살 받다 일어나다 상쾌하다
33           중요하다 미팅 옷 커피 쏟다           중요하다 미팅 옷 커피 쏟다
34       보너스 받다 부모님 선물 사 드리다       보너스 받다 부모님 선물 사 드리다
35  사랑 하다 사람과 헤어지다 눈물 멈추다 않다  사랑 하다 사람과 헤어지다 눈물 멈추다 않다

In [42]:
# 벡터화
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
# 독립, 종속 분리
x = vectorizer.fit_transform(dataset['cleaned_sentence'])
y = dataset['label']

from sklearn.model_selection import train_test_split
# 원래는 훈련, 테스트 분리하여 학습 후의 정확도를 확인
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [43]:
# 학습
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [44]:
model.score(x_test, y_test)

0.625

In [50]:
# 테스트
text = '자격증 시험에 합격했습니다'
vectir_text = vectorizer.transform([text])
res = model.predict(vectir_text)
print(f'{text} : {'긍정' if res[0] else '부정'}')

# 시험 떨어지다라는 데이터를 학습하지 못해서 결과가 정확하지 않음
text = '날씨가 화창한데 자격증 시험에 떨어졌습니다'
vectir_text = vectorizer.transform([text])
res = model.predict(vectir_text)
print(f'{text} : {'긍정' if res[0] else '부정'}')

자격증 시험에 합격했습니다 : 긍정
날씨가 화창한데 자격증 시험에 떨어졌습니다 : 긍정